import MainLayout from "../../components/main-layout/main-layout";
import "./globals.css";

export const metadata = {
  title: 'IT-Potion',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <MainLayout>
          {children}
        </MainLayout>
      </body>
    </html>
  )
}
